/*
 * This file is generated by jOOQ.
*/
package com.cml.learn.jooq.domain;


import com.cml.learn.jooq.domain.tables.Author;
import com.cml.learn.jooq.domain.tables.Book;
import com.cml.learn.jooq.domain.tables.BookStore;
import com.cml.learn.jooq.domain.tables.Language;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jooqtest extends SchemaImpl {

    private static final long serialVersionUID = 750516127;

    /**
     * The reference instance of <code>jooqtest</code>
     */
    public static final Jooqtest JOOQTEST = new Jooqtest();

    /**
     * The table <code>jooqtest.author</code>.
     */
    public final Author AUTHOR = com.cml.learn.jooq.domain.tables.Author.AUTHOR;

    /**
     * The table <code>jooqtest.book</code>.
     */
    public final Book BOOK = com.cml.learn.jooq.domain.tables.Book.BOOK;

    /**
     * The table <code>jooqtest.book_store</code>.
     */
    public final BookStore BOOK_STORE = com.cml.learn.jooq.domain.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>jooqtest.language</code>.
     */
    public final Language LANGUAGE = com.cml.learn.jooq.domain.tables.Language.LANGUAGE;

    /**
     * No further instances allowed
     */
    private Jooqtest() {
        super("jooqtest", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            Book.BOOK,
            BookStore.BOOK_STORE,
            Language.LANGUAGE);
    }
}
