/*
 * This file is generated by jOOQ.
*/
package com.cml.learn.jooq.domain;


import com.cml.learn.jooq.domain.tables.Author;
import com.cml.learn.jooq.domain.tables.Book;
import com.cml.learn.jooq.domain.tables.BookStore;
import com.cml.learn.jooq.domain.tables.Language;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooqtest
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooqtest.author</code>.
     */
    public static final Author AUTHOR = com.cml.learn.jooq.domain.tables.Author.AUTHOR;

    /**
     * The table <code>jooqtest.book</code>.
     */
    public static final Book BOOK = com.cml.learn.jooq.domain.tables.Book.BOOK;

    /**
     * The table <code>jooqtest.book_store</code>.
     */
    public static final BookStore BOOK_STORE = com.cml.learn.jooq.domain.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>jooqtest.language</code>.
     */
    public static final Language LANGUAGE = com.cml.learn.jooq.domain.tables.Language.LANGUAGE;
}
