spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3307/jooqtest?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout : 5000
      minimumIdle: 20
      readOnly: false
      autoCommit: false
      initialSize : 20
      maximumPoolSize : 100
      poolName: myHikari

server:
  port: 9082



cml:
  request-distribute:
    enable: true
    policy:
      - group: makeinvoice
        rate: 1
        enable: false
      - group: print
        rate: 2
      - group: rededit
        rate: 0.001