cml:
  request-distribute:
    enable: true
    rate: 0.01
    policy:
      - group: test
        rate: 1
        enable: false
      - group: print
        rate: 2
      - group: rededit
        rate: 0.001